# Autogenerated by update_action_versions.py on 2026-02-10T22:02:34-05:00
#
# This file centralizes pinned versions for GitHub Actions referenced by
# xcookie/builders/github_actions.py
#
# Keys are "owner/repo" (without the "@").
# Values are the ref to pin to (usually a tag like "v4.2.2").

from __future__ import annotations

ACTION_VERSIONS = {
    'actions/checkout': 'v6.0.2',
    'actions/download-artifact': 'v7.0.0',
    'actions/setup-python': 'v6.2.0',
    'actions/upload-artifact': 'v6.0.0',
    'codecov/codecov-action': 'v5.5.2',
    'docker/setup-qemu-action': 'v3.7.0',
    'ibnesayeed/setup-ipfs': '0.6.0',
    'ilammy/msvc-dev-cmd': 'v1.13.0',
    'maxim-lobanov/setup-xcode': 'v1.6.0',
    'pypa/cibuildwheel': 'v3.3.1',
    'softprops/action-gh-release': 'v2.5.0',
}
